document.write("<img src=\"asset/logo.png\" style=\"width:308px;height:110px;display:block;margin-left:auto;margin-right:auto;\">");
document.write("    <nav class=\"navbar\">");
document.write("      <div>");
document.write("        <a href=\"index.html\">HOME<\/a>");
document.write("        <a href=\"contact.html\">CONTACT<\/a>");
document.write("        <a href=\"forum-test.html\">DOWNLOAD<\/a>");
document.write("        <a href=\"about.html\">ABOUT<\/a>");
document.write("        <a href=\"forum-test.html\">FAQ<\/a>");
document.write("      <\/div>");
document.write("    <\/nav>");
